# -*- coding: utf-8 -*-
"""ML_INTERNAL_EXAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rLtc-l6bArLKBsC_fY4MYphrdj_fKrl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

df = pd.read_csv('/content/data.csv')
df.info()

df.describe()

df["Bare Nuclei"] = df["Bare Nuclei"].apply(lambda x: int(x) if x.isnumeric() else np.nan)

df.isna().sum()

df["Bare Nuclei"].fillna(df["Bare Nuclei"].mean(),inplace=True)

df["Class"].replace({2:0,4:1},inplace=True)

df.info()

sns.heatmap(df.corr())

df = df.drop(columns=["Sample code number"],axis=1)

X = df.drop(columns=["Class"],axis=1).to_numpy()
y = df["Class"].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

def sigmoid(x):
  return 1/(1+np.exp(-x))

def delta_rule(X,y,epochs,lr):
  X = np.hstack((X,np.ones((X.shape[0],1))))

  total_records,columns = X.shape

  w = np.zeros(columns)

  error_old = 999999

  for i in range(epochs):
    error_l = []
    for rec,acty in zip(X,y):
      net = np.dot(w,rec)
      y_pred = sigmoid(net)

      error = acty - y_pred
      error_l.append(error**2)


      w += lr * error * rec

    av = np.mean(error_l)
    precise = abs(error_old - av)

    if precise < 0.00001:
      break
    error_old = av
    if i % 10 == 0:
      print(i,precise)

  return w

def predict(X,w):
  X = np.hstack((X,np.ones((X.shape[0],1))))
  y_pred = sigmoid(np.dot(X,w))
  y_pred = np.where(y_pred>0.5,1,0)
  return y_pred

w = delta_rule(X_train,y_train,1000,0.01)
w

pred_y = predict(X_test,w)

accuracy_score(y_test,pred_y)

conf = confusion_matrix(y_test,pred_y)
print(conf)
sns.heatmap(conf,annot=True)

print(classification_report(y_test,pred_y))